spring:
  profiles:
    active: test
  application:
    name: quartz-pro
  #关闭redis的配置
  #redis:
    #pool:
      #max-active: 1000
      #max-idle: 100
      #max-wait: 10000
      #min-idle: 50
    #timeout: 3000
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            isClustered: true

server:
  port: 8888

---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grafana?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=true&cachePrepStmts=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

server:
  port: 8887